### ISSUE TITLE
Replace / add config settings by riak_conf dict fails if it is not defined

### ISSUE THREAD

**Issue by TJC** [basho-labs/ansible-riak#21]
In the current dev-2.x branch, we have this action item:
```
- name: Replace / add config settings to riak.conf
  lineinfile: "dest=/etc/riak/riak.conf regexp='^#{0,1}{{ item.key|replace('-','.')  }} = .+$' line='{{ item.key|replace('-','.') }} = {{ item.value }}'"
  tags: configfiles
  when: riak_conf is defined
  with_dict: riak_conf
```

Unfortunately this fails with an error, "with_dict expects a dict", if riak_conf  is undefined. Even though there is a conditional above that looks like it should prevent this item running at all.

(riak_conf can be optionally uncommented and defined in defaults/main.yml)

# Note

The same issue applies to the security.yml tasks and their related (and commented-out) parameters in defaults.yml

**Comment by jsmartin** [comment]
Quite frankly, using lineinfile is not a good way to manage a configuration file.  It should be templated using the template module.

**Comment by TJC** [comment]
That's the way I've always managed Riak configs myself.. I assumed that there must be some reason for doing it the way it was in there, though. Would be happy to see it changed to a template-based system myself though.

**Comment by christophermancini** [comment]
I initially planned on templating it tbh. After discussions with a co-worker who had worked on the ansible stuff in the past, he pushed for an approach that would require less maintenance should we add, deprecate, or modify help text for a config option in Riak, because this role would not require an update.

W.r.t. the issue at hand, I am glad you caught this, as I did not notice it because I had a riak_conf dictionary defined in my environment, https://github.com/basho-labs/riak-clients-vagrant/blob/master/provisioning/roles/integration_testing/defaults/main.yml

I am surprised that the when: riak_conf is defined does not catch this. Do you think this behavior from Ansible is logical or should we bring it up in the community?

In the meantime, you think leaving riak_conf uncommented within defaults.yml with a few simple defaults would be an acceptable workaround?

**Comment by jsmartin** [comment]
You have shifted the complexity of the configuration file onto the configuration management system.  It's less declarative, harder to read, harder to debug, harder to understand.  Aim for simple.  

What you won't find is any roles for apache, mysql, ntp, etc that attempt to abstract every single possible configuration file parameter.  They are all templated.

**Comment by TJC** [comment]
I agree. You might be keeping the original config comments in place, but if all the config is done in Ansible, no-one will see them - -they'll be editing the Ansible config. So there's nothing to lose by just using a template; maybe with a comment at the top that suggests users check the distributed version to get the latest info, and have a link to the online config too?

**Comment by TJC** [comment]
See pull request #27 for a first pass at this. It's basic and really needs more variables and documentation for them added, but I am a bit rushed this week :(

**Comment by christophermancini** [comment]
This is no longer an 'issue' with the merge of pr #27
