### ISSUE TITLE
Buckets/Security tasks fail on repeated runs

### ISSUE THREAD

**Issue by TJC** [basho-labs/ansible-riak#25]
In dev-2.x branch, the buckets.yml and security.yml tasks will fail if re-run, throwing errors because the things they try to create have already been created.

Really they should have some kind of "only create if thing doesn't exist" logic added.

**Comment by jsmartin** [comment]
The tasks should be idempotent.  It's probably best to add a feature to the riak ansible module to support this.

**Comment by christophermancini** [comment]
You are probably right, I added both of these components pretty quickly. Fortunately, the only one that truly 'fails' is bucket-type create, the rest report back as changed and I believe just overwrite the previous value internally with Riak.

For buckets, we should be able to simply register a var from the results of riak-admin bucket-type list and us '.stdout.find' to verify if it is already in the list and if it is activated, otherwise skip it.

Security would probably be more challenging because its output is in tables. I am open to suggestions on how to approach that.

**Comment by jsmartin** [comment]
If it's only in tables, that's too bad.  Have someone make the output optionally machine consumable -- like json.  Otherwise goodluck parsing the tables :).

**Comment by christophermancini** [comment]
For now, I am going to close this ticket since at the moment there is nothing I can do. When updates are made to riak-admin cli tool, I will address this issue.
