### ISSUE TITLE
ansible-riak/tasks/main.yml on dev 2.x not idempotent

### ISSUE THREAD

**Issue by jsmartin** [basho-labs/ansible-riak#26]
The first task stops riak, then it goes on to start riak at the end.  Which means riak is always going to be stopped and started every time the role is used, which I'm guessing is not the desired behavior.

**Comment by christophermancini** [comment]
I am very much open to suggestions here, as I am not really an ops guy and I really only use Ansible for my dev environments which will be different from how it would be used in a production environment. Do you think the better option her would be to restart Riak after the config has been updated instead of doing the stop -> start?

**Comment by jsmartin** [comment]
The use of a "notify" to a "handler" to restart riak on package or config file update is the way to go, for sure.

**Comment by TJC** [comment]
100% agree that we shouldn't be needlessly restarting Riak every time Ansible runs.
The "notify" method is the way forward.

**Comment by mjbrender** [comment]
FYI that PR #22 has been accepted. Please open up another PR to address this discussion @TJC. Thank you so much @jsmartin for confirming the best behavior from an Ansible POV :+1:

**Comment by christophermancini** [comment]
I refreshed my knowledge of handlers and you guys are right, notify is the best option because they only bounce Riak if changes have occurred. @TJC Let me know if you have already made changes to use notify instead of the stop - start, otherwise I will make those changes sometime in the next few days.

**Comment by TJC** [comment]
Hi Chris,
I haven't started on that work yet.

**Comment by TJC** [comment]
I think this can be closed now, as you've merged pull request #27

**Comment by christophermancini** [comment]
Thans @TJC
